[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.21.3", features = ["rand"] }
indicatif = "0.17.0"
rand = "0.8.5"
stb_image = "0.2.4"
